import { GEN_TYPES, TASK_STATUSES } from "./types";
import type { GenerationTask } from "./types";

const now = Date.now();
const minutesAgo = (minutes: number) => now - minutes * 60_000;

export const GENERATION_QUEUE_SEED: GenerationTask[] = [
  {
    id: "q-1",
    type: GEN_TYPES.IMAGE,
    status: TASK_STATUSES.RUNNING,
    prompt: "Кинематографичный портрет путешественника в пустыне, мягкий оранжевый свет",
    providerId: "midjourney",
    modelName: "Midjourney v7",
    credits: 45,
    createdAt: minutesAgo(1),
    progress: 41,
    etaSeconds: 36,
  },
  {
    id: "q-2",
    type: GEN_TYPES.TEXT,
    status: TASK_STATUSES.RUNNING,
    prompt: "Сформулируй 5 вариантов слогана для SaaS-платформы аналитики",
    providerId: "chatgpt",
    modelName: "GPT-4o",
    credits: 6,
    createdAt: minutesAgo(3),
    progress: 72,
    etaSeconds: 12,
  },
  {
    id: "q-3",
    type: GEN_TYPES.VIDEO,
    status: TASK_STATUSES.QUEUED,
    prompt: "Дрон-облет горного озера на рассвете, 8 секунд, плавное движение",
    providerId: "veo",
    modelName: "Veo 3",
    credits: 120,
    createdAt: minutesAgo(5),
    progress: 0,
    etaSeconds: 130,
  },
  {
    id: "q-4",
    type: GEN_TYPES.AUDIO,
    status: TASK_STATUSES.QUEUED,
    prompt: "Lo-fi трек 90 BPM с теплым пиано и винил-шумом, 2 минуты",
    providerId: "suno",
    modelName: "Suno v4",
    credits: 60,
    createdAt: minutesAgo(7),
    progress: 0,
    etaSeconds: 95,
  },
  {
    id: "q-5",
    type: GEN_TYPES.IMAGE,
    status: TASK_STATUSES.QUEUED,
    prompt: "Иллюстрация интерьера уютного кафе в стиле сканди, изометрия",
    providerId: "flux",
    modelName: "Flux 1.1 Pro",
    credits: 30,
    createdAt: minutesAgo(10),
    progress: 0,
    etaSeconds: 42,
  },
  {
    id: "q-6",
    type: GEN_TYPES.VIDEO,
    status: TASK_STATUSES.DONE,
    prompt: "Таймлапс ночного города, неон, мягкий bloom, 6 секунд",
    providerId: "kling",
    modelName: "Kling 2.5 Turbo",
    credits: 75,
    createdAt: minutesAgo(15),
    progress: 100,
    etaSeconds: 0,
  },
  {
    id: "q-7",
    type: GEN_TYPES.TEXT,
    status: TASK_STATUSES.DONE,
    prompt: "Сделай краткий plan-of-action для запуска лендинга за 48 часов",
    providerId: "claude",
    modelName: "Claude Sonnet 4.5",
    credits: 8,
    createdAt: minutesAgo(20),
    progress: 100,
    etaSeconds: 0,
  },
  {
    id: "q-8",
    type: GEN_TYPES.IMAGE,
    status: TASK_STATUSES.FAILED,
    prompt: "Постер в стиле ретрофутуризм: теплые тона, зерно, геометрические формы",
    providerId: "nano-banana",
    modelName: "Nano Banana",
    credits: 35,
    createdAt: minutesAgo(24),
    progress: 63,
    etaSeconds: 0,
    errorMessage: "Модель временно недоступна",
  },
  {
    id: "q-9",
    type: GEN_TYPES.AUDIO,
    status: TASK_STATUSES.CANCELED,
    prompt: "Озвучка интро для подкаста: уверенный женский голос, 25 секунд",
    providerId: "elevenlabs",
    modelName: "ElevenLabs v3",
    credits: 40,
    createdAt: minutesAgo(28),
    progress: 29,
    etaSeconds: 0,
  },
  {
    id: "q-10",
    type: GEN_TYPES.TEXT,
    status: TASK_STATUSES.QUEUED,
    prompt: "Черновик email-цепочки welcome для SaaS: 3 письма, дружелюбный тон",
    providerId: "chatgpt",
    modelName: "GPT-4o",
    credits: 7,
    createdAt: minutesAgo(31),
    progress: 0,
    etaSeconds: 26,
  },
];
